import { useEffect, useState } from "react";
import { ShieldCheck, Users, Package, BarChart3, ClipboardList, RotateCcw, UserCheck, UserX, History } from "lucide-react";
import api from "../services/api";
import AppShell from "../components/AppShell";
import StatCard from "../components/StatCard";

const AdminDashboard=()=>{
 const [tab,setTab]=useState("overview"),[dash,setDash]=useState(null),[users,setUsers]=useState([]),[products,setProducts]=useState([]),[orders,setOrders]=useState([]),[returns,setReturns]=useState([]),[logs,setLogs]=useState([]),[message,setMessage]=useState("");
 const load=async()=>{try{const [d,u,p,o,r,a]=await Promise.all([api.get("/dashboard/admin"),api.get("/users"),api.get("/products?limit=100"),api.get("/staff/orders?limit=100"),api.get("/returns"),api.get("/audit")]);setDash(d.data.dashboard);setUsers(u.data.users);setProducts(p.data.products);setOrders(o.data.orders);setReturns(r.data.requests);setLogs(a.data.logs)}catch(e){setMessage(e.response?.data?.message||"Unable to load admin data")}};
 useEffect(()=>{load()},[]);
 const updateUser=async(id,payload)=>{try{await api.patch(`/users/${id}`,payload);setMessage("User updated.");load()}catch(e){setMessage(e.response?.data?.message||"Unable to update user")}};
 return <AppShell title="Admin control center" subtitle="Manage users, products, orders, returns and application health.">
 {message&&<div className="notice">{message}</div>}
 <div className="tabs">{[["overview","Overview",BarChart3],["users","Users",Users],["products","Products",Package],["orders","Orders",ClipboardList],["returns","Returns",RotateCcw],["audit","Audit trail",History]].map(([id,l,I])=><button className={`tab ${tab===id?"active":""}`} key={id} onClick={()=>setTab(id)}><I size={15}/> {l}</button>)}</div>
 {tab==="overview"&&dash&&<div className="grid stats-grid"><StatCard icon={<Users size={19}/>} label="Active products" value={dash.activeProducts}/><StatCard icon={<ClipboardList size={19}/>} label="Orders" value={dash.totalOrders}/><StatCard icon={<BarChart3 size={19}/>} label="Revenue" value={`₹${dash.totalRevenue.toFixed(2)}`}/><StatCard icon={<ShieldCheck size={19}/>} label="Low-stock alerts" value={dash.lowStockProducts}/></div>}
 {tab==="users"&&<section className="panel"><div className="panel-title"><h2>User management</h2><span className="muted">{users.length} users</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.map(u=><tr key={u._id}><td><strong>{u.name}</strong><span className="muted">{u.email}</span></td><td><select className="select" value={u.role} onChange={e=>updateUser(u._id,{role:e.target.value})}>{["CUSTOMER","STAFF","MANAGER","ADMIN"].map(r=><option key={r}>{r}</option>)}</select></td><td><span className={`status ${u.isActive?"":"pill-danger"}`}>{u.isActive?"ACTIVE":"INACTIVE"}</span></td><td><button className={`btn ${u.isActive?"btn-danger":"btn-primary"}`} onClick={()=>updateUser(u._id,{isActive:!u.isActive})}>{u.isActive?<><UserX size={14}/> Deactivate</>:<><UserCheck size={14}/> Activate</>}</button></td></tr>)}</tbody></table></div></section>}
 {tab==="products"&&<section className="panel"><h2>Product catalog</h2><div className="table-wrap"><table className="data-table"><thead><tr><th>Name</th><th>Category</th><th>Price</th><th>Stock</th><th>Active</th></tr></thead><tbody>{products.map(p=><tr key={p._id}><td>{p.name}</td><td>{p.category}</td><td>₹{p.price.toFixed(2)}</td><td>{p.stock}</td><td>{p.isActive?"Yes":"No"}</td></tr>)}</tbody></table></div></section>}
 {tab==="orders"&&<section className="panel"><h2>All orders</h2><div className="table-wrap"><table className="data-table"><thead><tr><th>Order</th><th>Customer</th><th>Fulfillment</th><th>Status</th><th>Total</th></tr></thead><tbody>{orders.map(o=><tr key={o._id}><td>{o.orderNumber}</td><td>{o.customer?.name}</td><td>{o.fulfillmentType}</td><td><span className="status">{o.status}</span></td><td>₹{o.total.toFixed(2)}</td></tr>)}</tbody></table></div></section>}
 {tab==="audit"&&<section className="panel"><div className="panel-title"><div><h2>Security audit trail</h2><span className="muted">Admin-only record of sensitive actions</span></div><span className="status">{logs.length} events</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Entity</th><th>IP</th></tr></thead><tbody>{logs.map(log=><tr key={log._id}><td>{new Date(log.createdAt).toLocaleString()}</td><td><strong>{log.actor?.name||"System"}</strong><span className="muted">{log.actor?.role||"SYSTEM"}</span></td><td><span className="status pill-blue">{log.action}</span></td><td>{log.entityType}{log.entityId&&` · ${String(log.entityId).slice(-8)}`}</td><td className="muted">{log.ip||"—"}</td></tr>)}</tbody></table></div></section>}
 {tab==="returns"&&<section className="panel"><h2>Returns & exchanges</h2><div className="table-wrap"><table className="data-table"><thead><tr><th>Customer</th><th>Order</th><th>Type</th><th>Item</th><th>Status</th></tr></thead><tbody>{returns.map(r=><tr key={r._id}><td>{r.customer?.name}</td><td>{r.order?.orderNumber}</td><td>{r.type}</td><td>{r.item.name} × {r.item.quantity}</td><td><span className="status">{r.status}</span></td></tr>)}</tbody></table></div></section>}
 </AppShell>
};
export default AdminDashboard;
