import { useEffect, useState } from "react";
import { BarChart3, Package, AlertTriangle, ClipboardList, RotateCcw, Plus, Pencil, Trash2 } from "lucide-react";
import api from "../services/api";
import AppShell from "../components/AppShell";
import StatCard from "../components/StatCard";

const ManagerDashboard=()=>{
 const [tab,setTab]=useState("overview"),[dash,setDash]=useState(null),[products,setProducts]=useState([]),[orders,setOrders]=useState([]),[returns,setReturns]=useState([]),[message,setMessage]=useState(""),[edit,setEdit]=useState(null);
 const load=async()=>{try{const [d,p,o,r]=await Promise.all([api.get("/dashboard/admin"),api.get("/products?limit=100"),api.get("/staff/orders?limit=100"),api.get("/returns")]);setDash(d.data.dashboard);setProducts(p.data.products);setOrders(o.data.orders);setReturns(r.data.requests)}catch(e){setMessage(e.response?.data?.message||"Unable to load manager data")}};
 useEffect(()=>{load()},[]);
 const save=async(e)=>{e.preventDefault();try{if(edit._id)await api.patch(`/products/${edit._id}`,edit);else await api.post("/products",edit);setMessage("Product saved.");setEdit(null);load()}catch(e){setMessage(e.response?.data?.message||"Unable to save product")}};
 const remove=async(id)=>{if(!confirm("Remove this product from the storefront?"))return;try{await api.delete(`/products/${id}`);setMessage("Product removed.");load()}catch(e){setMessage(e.response?.data?.message||"Unable to remove product")}};
 return <AppShell title="Manager dashboard" subtitle="Monitor revenue, stock, orders and store performance.">
 {message&&<div className="notice">{message}</div>}
 <div className="tabs">{[["overview","Overview",BarChart3],["products","Products",Package],["orders","Orders",ClipboardList],["returns","Returns",RotateCcw]].map(([id,l,I])=><button className={`tab ${tab===id?"active":""}`} key={id} onClick={()=>setTab(id)}><I size={15}/> {l}</button>)}</div>
 {tab==="overview"&&dash&&<><div className="grid stats-grid"><StatCard icon={<Package size={19}/>} label="Active products" value={dash.activeProducts}/><StatCard icon={<ClipboardList size={19}/>} label="Total orders" value={dash.totalOrders}/><StatCard icon={<BarChart3 size={19}/>} label="Revenue" value={`₹${dash.totalRevenue.toFixed(2)}`}/><StatCard icon={<AlertTriangle size={19}/>} label="Low stock" value={dash.lowStockProducts}/></div><div className="two-col mt"><div className="panel"><div className="panel-title"><div><h3>Order health</h3><span className="muted">Current lifecycle mix</span></div><TrendingUp size={18} className="panel-accent"/></div><div className="list">{[["Pending",dash.pendingOrders,"bar-pending"],["Completed",dash.completedOrders,"bar-complete"],["Cancelled",dash.cancelledOrders,"bar-cancelled"]].map(x=>{const total=Math.max((dash.pendingOrders||0)+(dash.completedOrders||0)+(dash.cancelledOrders||0),1); return <div className="health-row" key={x[0]}><div className="list-item"><span>{x[0]}</span><strong>{x[1]}</strong></div><div className="health-track"><span className={x[2]} style={{width:`${Math.min(100,(x[1]/total)*100)}%`}} /></div></div>})}</div></div><div className="panel"><h3>Product health</h3><p className="muted">Low-stock products are flagged when stock is at or below their configured threshold.</p><button className="btn btn-primary" onClick={()=>setTab("products")}>Review inventory</button></div></div></>}
 {tab==="products"&&<section className="panel"><div className="panel-title"><h2>Product inventory</h2><button className="btn btn-primary" onClick={()=>setEdit({name:"",description:"",category:"",price:0,stock:0,lowStockThreshold:5,image:""})}><Plus size={16}/> Add product</button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Action</th></tr></thead><tbody>{products.map(p=><tr key={p._id}><td><strong>{p.name}</strong><span className="muted">{p.description}</span></td><td>{p.category}</td><td>₹{p.price.toFixed(2)}</td><td><span className={p.stock<=p.lowStockThreshold?"status pill-danger":"status"}>{p.stock}</span></td><td><div className="actions"><button className="btn btn-ghost" onClick={()=>setEdit({...p})}><Pencil size={14}/> Edit</button><button className="btn btn-danger" onClick={()=>remove(p._id)}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table></div></section>}
 {tab==="orders"&&<section className="panel"><div className="table-wrap"><table className="data-table"><thead><tr><th>Order</th><th>Customer</th><th>Status</th><th>Total</th></tr></thead><tbody>{orders.map(o=><tr key={o._id}><td>{o.orderNumber}</td><td>{o.customer?.name}</td><td><span className="status">{o.status}</span></td><td>₹{o.total.toFixed(2)}</td></tr>)}</tbody></table></div></section>}
 {tab==="returns"&&<section className="panel"><div className="table-wrap"><table className="data-table"><thead><tr><th>Customer</th><th>Type</th><th>Item</th><th>Status</th></tr></thead><tbody>{returns.map(r=><tr key={r._id}><td>{r.customer?.name}</td><td>{r.type}</td><td>{r.item.name} × {r.item.quantity}</td><td><span className="status">{r.status}</span></td></tr>)}</tbody></table></div></section>}
 {edit&&<ProductModal value={edit} setValue={setEdit} onClose={()=>setEdit(null)} onSave={save}/>}
 </AppShell>
};
const ProductModal=({value,setValue,onClose,onSave})=><div className="modal-backdrop"><div className="modal"><div className="modal-header"><h2>{value._id?"Edit product":"New product"}</h2><button className="close" onClick={onClose}>×</button></div><form className="form-grid" onSubmit={onSave}>{["name","category","price","stock","lowStockThreshold","image"].map(k=><div className="field" key={k}><label>{k.replace(/([A-Z])/g," $1")}</label><input required={["name","category","price"].includes(k)} className="input" type={["price","stock","lowStockThreshold"].includes(k)?"number":"text"} value={value[k]??""} onChange={e=>setValue({...value,[k]:["price","stock","lowStockThreshold"].includes(k)?Number(e.target.value):e.target.value})}/></div>)}<div className="field full"><label>Description</label><textarea className="textarea" rows="3" value={value.description||""} onChange={e=>setValue({...value,description:e.target.value})}/></div><div className="field full"><button className="btn btn-primary">Save product</button></div></form></div></div>;
export default ManagerDashboard;
