import { useEffect, useState } from "react";
import { ClipboardList, RotateCcw, Warehouse, RefreshCw, CheckCircle2, Zap } from "lucide-react";
import api from "../services/api";
import AppShell from "../components/AppShell";
import StatCard from "../components/StatCard";

const StaffDashboard=()=>{
 const [tab,setTab]=useState("orders"),[orders,setOrders]=useState([]),[returns,setReturns]=useState([]),[dash,setDash]=useState({}),[filter,setFilter]=useState(""),[fulfillment,setFulfillment]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const [o,d,r]=await Promise.all([api.get(`/staff/orders?limit=100${filter?`&status=${filter}`:""}${fulfillment?`&fulfillmentType=${fulfillment}`:""}`),api.get("/dashboard/staff"),api.get("/returns")]);setOrders(o.data.orders);setDash(d.data.dashboard);setReturns(r.data.requests)}catch(e){setMessage(e.response?.data?.message||"Unable to load operations")}finally{setLoading(false)}};
 useEffect(()=>{load()},[filter,fulfillment]);
 const update=async(id,status)=>{try{await api.patch(`/staff/orders/${id}/status`,{status});setMessage("Order status updated.");load()}catch(e){setMessage(e.response?.data?.message||"Status update failed.")}};
 const process=async(id,status)=>{try{await api.patch(`/returns/${id}`,{status});setMessage("Return request updated.");load()}catch(e){setMessage(e.response?.data?.message||"Unable to process request.")}};
 const next=(o)=>({PLACED:"CONFIRMED",CONFIRMED:"PREPARING",PREPARING:"READY",READY:o.fulfillmentType==="PICKUP"?"PICKED_UP":"OUT_FOR_DELIVERY",OUT_FOR_DELIVERY:"DELIVERED"})[o.status];
 if(loading)return <div className="app-loading">Loading store operations…</div>;
 return <AppShell title="Store operations" subtitle="Prepare orders, manage pickups, deliveries and returns.">
 {message&&<div className="notice">{message}</div>}
 <div className="grid stats-grid mb">{[["PLACED","New orders"],["PREPARING","Preparing"],["READY","Ready"],["OUT_FOR_DELIVERY","Out for delivery"]].map(([k,l])=><StatCard key={k} icon={<ClipboardList size={19}/>} label={l} value={dash[k]||0}/>)}</div>
 <div className="ops-focus"><div><span className="focus-kicker"><Zap size={13}/> Live operations</span><h3>Keep the queue moving</h3><p>Work the earliest orders first, then clear pickup and delivery handoffs.</p></div><div className="focus-flow"><span>PLACED</span><i>→</i><span>PREPARING</span><i>→</i><span>READY</span><i>→</i><span>FULFILLED</span></div></div>
 <div className="tabs">{[["orders","Orders",ClipboardList],["returns","Returns & exchanges",RotateCcw],["inventory","Inventory",Warehouse]].map(([id,l,I])=><button className={`tab ${tab===id?"active":""}`} key={id} onClick={()=>setTab(id)}><I size={15}/> {l}</button>)}<button className="tab" onClick={load}><RefreshCw size={15}/> Refresh</button></div>
 {tab==="orders"&&<section className="panel"><div className="toolbar"><select className="select" style={{maxWidth:220}} value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All statuses</option>{["PLACED","CONFIRMED","PREPARING","READY","OUT_FOR_DELIVERY","DELIVERED","PICKED_UP","CANCELLED"].map(s=><option key={s}>{s}</option>)}</select><select className="select" style={{maxWidth:220}} value={fulfillment} onChange={e=>setFulfillment(e.target.value)}><option value="">All fulfillment</option><option value="PICKUP">Pickup</option><option value="DELIVERY">Delivery</option></select></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Order</th><th>Customer</th><th>Fulfillment</th><th>Total</th><th>Status</th><th>Action</th></tr></thead><tbody>{orders.map(o=><tr key={o._id}><td><strong>{o.orderNumber}</strong><span className="muted">{new Date(o.createdAt).toLocaleString()}</span></td><td>{o.customer?.name}<span className="muted">{o.customer?.email}</span></td><td>{o.fulfillmentType}{o.scheduledPickupAt&&<span className="muted">{new Date(o.scheduledPickupAt).toLocaleString()}</span>}</td><td>₹{o.total.toFixed(2)}</td><td><span className="status">{o.status}</span></td><td>{next(o)&&<button className="btn btn-primary" onClick={()=>update(o._id,next(o))}><CheckCircle2 size={15}/> {next(o).replaceAll("_"," ")}</button>}</td></tr>)}</tbody></table>{!orders.length&&<div className="empty">No orders match the filters.</div>}</div></section>}
 {tab==="returns"&&<section className="panel"><div className="table-wrap"><table className="data-table"><thead><tr><th>Customer</th><th>Request</th><th>Reason</th><th>Status</th><th>Action</th></tr></thead><tbody>{returns.map(r=><tr key={r._id}><td>{r.customer?.name}<span className="muted">{r.customer?.email}</span></td><td><strong>{r.type}</strong><span className="muted">{r.item.name} × {r.item.quantity} · {r.order?.orderNumber}</span></td><td>{r.reason}</td><td><span className="status">{r.status}</span></td><td><div className="actions">{r.status==="PENDING"&&<><button className="btn btn-primary" onClick={()=>process(r._id,"APPROVED")}>Approve</button><button className="btn btn-danger" onClick={()=>process(r._id,"REJECTED")}>Reject</button></>}{r.status==="APPROVED"&&<button className="btn btn-dark" onClick={()=>process(r._id,"COMPLETED")}>Complete</button>}</div></td></tr>)}</tbody></table>{!returns.length&&<div className="empty">No return requests.</div>}</div></section>}
 {tab==="inventory"&&<section className="panel"><p className="muted">Inventory editing is available to managers and administrators. Staff can monitor order flow here.</p><div className="grid stats-grid"><StatCard icon={<Warehouse size={19}/>} label="Completed pickups" value={dash.PICKED_UP||0}/><StatCard icon={<Warehouse size={19}/>} label="Delivered" value={dash.DELIVERED||0}/><StatCard icon={<RotateCcw size={19}/>} label="Cancelled" value={dash.CANCELLED||0}/><StatCard icon={<ClipboardList size={19}/>} label="Total orders" value={Object.values(dash).reduce((a,b)=>a+b,0)}/></div></section>}
 </AppShell>
};
export default StaffDashboard;
